# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
